/**
 * Lead CRM constants.
 * Values mirror Prisma Lead* enums (generated by parent schema slice).
 */

export const LEAD_SOURCES = [
  'META_LEAD_FORM',
  'WEBSITE',
  'MANUAL',
  'PHONE_IN',
  'FACEBOOK_MESSENGER',
  'OTHER',
] as const;
export type LeadSourceValue = (typeof LEAD_SOURCES)[number];

export const LEAD_CREATIVE_TYPES = ['VIDEO', 'GRAPHIC', 'UNKNOWN'] as const;
export type LeadCreativeTypeValue = (typeof LEAD_CREATIVE_TYPES)[number];

export const LEAD_STAGES = [
  'NEW',
  'CONTACTED',
  'QUALIFYING',
  'DOCUMENTS_REQUESTED',
  'APPLICATION_SUBMITTED',
  'APPROVED',
  'VEHICLE_SELECTED',
  'CLOSED_WON',
  'CLOSED_LOST',
] as const;
export type LeadStageValue = (typeof LEAD_STAGES)[number];

export const LEAD_QUALIFICATION_STATUSES = [
  'UNASSESSED',
  'QUALIFIED',
  'UNQUALIFIED',
] as const;
export type LeadQualificationStatusValue =
  (typeof LEAD_QUALIFICATION_STATUSES)[number];

export const LEAD_DISQUALIFICATION_REASONS = [
  'UBER_BOLT',
  'AFFORDABILITY',
  'INVALID_OR_NO_DRIVERS_LICENCE',
  'UNREACHABLE',
  'NOT_INTERESTED',
  'OUTSIDE_REQUIREMENTS',
  'NO_SUITABLE_VEHICLE',
  'DUPLICATE',
  'OTHER',
] as const;
export type LeadDisqualificationReasonValue =
  (typeof LEAD_DISQUALIFICATION_REASONS)[number];

export const LEAD_LOSS_REASONS = [
  'APPLICATION_DECLINED',
  'CUSTOMER_WITHDREW',
  'NO_SUITABLE_VEHICLE',
  'UNREACHABLE',
  'DUPLICATE',
  'OTHER',
] as const;
export type LeadLossReasonValue = (typeof LEAD_LOSS_REASONS)[number];

export const LEAD_CONTACT_CHANNELS = [
  'PHONE',
  'WHATSAPP',
  'EMAIL',
  'SMS',
  'OTHER',
] as const;
export type LeadContactChannelValue = (typeof LEAD_CONTACT_CHANNELS)[number];

export const LEAD_DELIVERY_SYSTEMS = ['NONE', 'VMG', 'OTHER'] as const;
export type LeadDeliverySystemValue = (typeof LEAD_DELIVERY_SYSTEMS)[number];

/** Sources Sales may use when creating a lead (auto-assigned to creator). */
export const SALES_CREATE_SOURCES = ['MANUAL', 'PHONE_IN'] as const;
export type SalesCreateSource = (typeof SALES_CREATE_SOURCES)[number];

export const TERMINAL_LEAD_STAGES = ['CLOSED_WON', 'CLOSED_LOST'] as const;

export const ATTRIBUTION_FIELD_KEYS = [
  'sourceDetail',
  'platform',
  'campaignId',
  'campaignName',
  'adSetId',
  'adSetName',
  'adId',
  'adName',
  'formId',
  'formName',
  'creativeType',
  'creativeLabel',
  'utmSource',
  'utmMedium',
  'utmCampaign',
  'utmContent',
  'externalLeadId',
  'sourceCreatedAt',
] as const;

export type AttributionFieldKey = (typeof ATTRIBUTION_FIELD_KEYS)[number];
